### ISSUE TITLE
Unable to run density-heavy scenario with 80K pods

### ISSUE THREAD

**Issue by igsilya** [dceara/ovn-heater#133]
Somewhere around 40K load balancers, ovn-heater aborts due to `DEFAULT_VIP_SUBNET` being exhausted:

```
2022-09-21 00:04:30,710 | ovn_workload |INFO| Creating load balancer lb_density_heavy_79868
2022-09-21 00:04:32,356 | ovn_workload |INFO| Creating load balancer lb_density_heavy_79870
2022-09-21 00:04:34,006 | ovn_workload |INFO| Creating load balancer lb_density_heavy_79872
2022-09-21 00:04:35,558 | ovn_context  |INFO| Waiting for the OVN state synchronization
2022-09-21 00:05:21,236 | ovn_context  |INFO| Exiting context density_heavy_startup
Traceback (most recent call last):
  File "/root/ovn-heater/ovn-tester/ovn_tester.py", line 314, in <module>
    test.run(ovn, global_cfg)
  File "/root/ovn-heater/ovn-tester/tests/density_heavy.py", line 78, in run
    DEFAULT_VIP_SUBNET, [[ports[i]]])
  File "/root/ovn-heater/ovn-tester/tests/density_heavy.py", line 50, in create_lb
    vip_net = DEFAULT_VIP_SUBNET.next(len(self.lb_list))
  File "/root/ovn-heater/runtime/venv/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 1251, in next
    ip_copy += step
  File "/root/ovn-heater/runtime/venv/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 1102, in __iadd__
    raise IndexError('increment exceeds address boundary!')
IndexError: increment exceeds address boundary!

```

**Comment by dceara** [comment]
Oh, density_heavy and service_route VIP subnets are defined as `100.0.0.0/16` and `90.0.0.0/16`.  The easy "fix" would be to make these /8.  We already do that in ovn_tester.py for the "basic" load balancers.  What do you think?

**Comment by igsilya** [comment]
Isn't it `DEFAULT_VIP_SUBNET` that gets exhausted?  This one is `4.0.0.0/8`.

**Comment by dceara** [comment]
> Isn't it `DEFAULT_VIP_SUBNET` that gets exhausted? This one is `4.0.0.0/8`.

It's a bit unfortunate but `DEFAULT_VIP_SUBNET` is defined in multiple places.  The ones in density_heavy.py and in service_route.py are /8.

**Comment by igsilya** [comment]
> > Isn't it `DEFAULT_VIP_SUBNET` that gets exhausted? This one is `4.0.0.0/8`.
> 
> It's a bit unfortunate but `DEFAULT_VIP_SUBNET` is defined in multiple places. The ones in density_heavy.py and in service_route.py are /8.

I suppose, you meant /16.
Oh. OK.  I see.  I guess, making them /8 should do the trick then.

**Comment by dceara** [comment]
> > > Isn't it `DEFAULT_VIP_SUBNET` that gets exhausted? This one is `4.0.0.0/8`.
> > 
> > 
> > It's a bit unfortunate but `DEFAULT_VIP_SUBNET` is defined in multiple places. The ones in density_heavy.py and in service_route.py are /8.
> 
> I suppose, you meant /16. Oh. OK. I see. I guess, making them /8 should do the trick then.

Yes, I did, sorry about the confusion.  I posted a fix:
https://github.com/dceara/ovn-heater/pull/134

**Comment by igsilya** [comment]
I still didn't test that, but looking at how load balancers are configured, it seems like we stride across high bits in the address:
```
2022-09-22T01:39:13.934Z|72863|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_98-tcp protocol=tcp
2022-09-22T01:39:13.939Z|72864|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_98-udp protocol=udp
2022-09-22T01:39:13.943Z|72865|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_98-sctp protocol=sctp
2022-09-22T01:39:13.947Z|72866|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 66948c7b-dae5-4496-9d3a-f8b0d49ffb93
2022-09-22T01:39:13.954Z|72867|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer b967ad77-f6b4-4dfa-9948-ede8cc2a8078
2022-09-22T01:39:13.960Z|72868|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer d0754399-b545-410f-8b7d-c641ab3cee72
2022-09-22T01:39:13.967Z|72869|ovn_dbctl|INFO|Running command run -- set Load_Balancer 66948c7b-dae5-4496-9d3a-f8b0d49ffb93 "vips:\"100.49.0.1:80\"=\"16.99.0.11:8080\""
2022-09-22T01:39:13.971Z|72870|ovn_dbctl|INFO|Running command run -- set Load_Balancer b967ad77-f6b4-4dfa-9948-ede8cc2a8078 "vips:\"100.49.0.1:80\"=\"16.99.0.11:8080\""
2022-09-22T01:39:13.975Z|72871|ovn_dbctl|INFO|Running command run -- set Load_Balancer d0754399-b545-410f-8b7d-c641ab3cee72 "vips:\"100.49.0.1:80\"=\"16.99.0.11:8080\""
2022-09-22T01:39:13.982Z|72872|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_100-tcp protocol=tcp
2022-09-22T01:39:13.986Z|72873|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_100-udp protocol=udp
2022-09-22T01:39:13.992Z|72874|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_100-sctp protocol=sctp
2022-09-22T01:39:13.996Z|72875|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 69d203df-e40d-4dae-93cf-8480a9d1105a
2022-09-22T01:39:14.003Z|72876|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 46a93a9e-96a1-40bf-89e4-9bf03e715774
2022-09-22T01:39:14.009Z|72877|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer fb7ba85e-44de-407a-b40f-d942ac5d5084
2022-09-22T01:39:14.016Z|72878|ovn_dbctl|INFO|Running command run -- set Load_Balancer 69d203df-e40d-4dae-93cf-8480a9d1105a "vips:\"100.50.0.1:80\"=\"16.101.0.11:8080\""
2022-09-22T01:39:14.020Z|72879|ovn_dbctl|INFO|Running command run -- set Load_Balancer 46a93a9e-96a1-40bf-89e4-9bf03e715774 "vips:\"100.50.0.1:80\"=\"16.101.0.11:8080\""
2022-09-22T01:39:14.024Z|72880|ovn_dbctl|INFO|Running command run -- set Load_Balancer fb7ba85e-44de-407a-b40f-d942ac5d5084 "vips:\"100.50.0.1:80\"=\"16.101.0.11:8080\""
2022-09-22T01:39:14.031Z|72881|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_102-tcp protocol=tcp
2022-09-22T01:39:14.035Z|72882|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_102-udp protocol=udp
2022-09-22T01:39:14.039Z|72883|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_102-sctp protocol=sctp
2022-09-22T01:39:14.044Z|72884|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 3acc9bf4-01fc-41f3-bdef-9b450d88290e
2022-09-22T01:39:14.050Z|72885|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 28be49be-5d40-4abc-a827-2a213b3e0e3a
2022-09-22T01:39:14.057Z|72886|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 817a66bc-a3d6-44e3-87ee-68dcc27b0274
2022-09-22T01:39:14.063Z|72887|ovn_dbctl|INFO|Running command run -- set Load_Balancer 3acc9bf4-01fc-41f3-bdef-9b450d88290e "vips:\"100.51.0.1:80\"=\"16.103.0.11:8080\""
2022-09-22T01:39:14.070Z|72888|ovn_dbctl|INFO|Running command run -- set Load_Balancer 28be49be-5d40-4abc-a827-2a213b3e0e3a "vips:\"100.51.0.1:80\"=\"16.103.0.11:8080\""
2022-09-22T01:39:14.074Z|72889|ovn_dbctl|INFO|Running command run -- set Load_Balancer 817a66bc-a3d6-44e3-87ee-68dcc27b0274 "vips:\"100.51.0.1:80\"=\"16.103.0.11:8080\""
...
2022-09-22T02:59:11.388Z|200936|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28476-tcp protocol=tcp
2022-09-22T02:59:11.393Z|200937|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28476-udp protocol=udp
2022-09-22T02:59:11.398Z|200938|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28476-sctp protocol=sctp
2022-09-22T02:59:11.403Z|200939|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 654002d4-ce68-4a7f-a7f0-65c85cc9deb2
2022-09-22T02:59:11.570Z|200940|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 63ad0288-9af4-4621-9e12-9313690fb511
2022-09-22T02:59:11.737Z|200941|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 2c00faa2-ee82-48ed-aec7-e206391fb527
2022-09-22T02:59:11.904Z|200942|ovn_dbctl|INFO|Running command run -- set Load_Balancer 654002d4-ce68-4a7f-a7f0-65c85cc9deb2 "vips:\"155.158.0.1:80\"=\"16.227.0.124:8080\""
2022-09-22T02:59:11.939Z|200943|ovn_dbctl|INFO|Running command run -- set Load_Balancer 63ad0288-9af4-4621-9e12-9313690fb511 "vips:\"155.158.0.1:80\"=\"16.227.0.124:8080\""
2022-09-22T02:59:11.945Z|200944|ovn_dbctl|INFO|Running command run -- set Load_Balancer 2c00faa2-ee82-48ed-aec7-e206391fb527 "vips:\"155.158.0.1:80\"=\"16.227.0.124:8080\""
2022-09-22T02:59:11.952Z|200945|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28478-tcp protocol=tcp
2022-09-22T02:59:11.957Z|200946|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28478-udp protocol=udp
2022-09-22T02:59:11.962Z|200947|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28478-sctp protocol=sctp
2022-09-22T02:59:11.969Z|200948|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 212458bc-ab4e-40b9-80f3-d6e013d3de58
2022-09-22T02:59:12.136Z|200949|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer df1a2dd6-fc68-4696-ae17-9e6c813ac9e5
2022-09-22T02:59:12.303Z|200950|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 477d07f7-0d0c-4722-9c09-bbe5e74549ed
2022-09-22T02:59:12.470Z|200951|ovn_dbctl|INFO|Running command run -- set Load_Balancer 212458bc-ab4e-40b9-80f3-d6e013d3de58 "vips:\"155.159.0.1:80\"=\"16.229.0.124:8080\""
2022-09-22T02:59:12.505Z|200952|ovn_dbctl|INFO|Running command run -- set Load_Balancer df1a2dd6-fc68-4696-ae17-9e6c813ac9e5 "vips:\"155.159.0.1:80\"=\"16.229.0.124:8080\""
2022-09-22T02:59:12.511Z|200953|ovn_dbctl|INFO|Running command run -- set Load_Balancer 477d07f7-0d0c-4722-9c09-bbe5e74549ed "vips:\"155.159.0.1:80\"=\"16.229.0.124:8080\""
2022-09-22T02:59:12.517Z|200954|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28480-tcp protocol=tcp
2022-09-22T02:59:12.524Z|200955|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28480-udp protocol=udp
2022-09-22T02:59:12.529Z|200956|ovn_dbctl|INFO|Running command run -- create Load_Balancer name=lb_density_heavy_28480-sctp protocol=sctp
2022-09-22T02:59:12.536Z|200957|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 8ba7097d-fc98-4181-85a2-65168593b089
2022-09-22T02:59:12.703Z|200958|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 37ddb7e1-60da-4b74-a501-429e299f10c9
2022-09-22T02:59:12.870Z|200959|ovn_dbctl|INFO|Running command run -- add Load_Balancer_Group d7faff09-2274-4fab-82d4-70ad9ec35c60 load_balancer 3cc166df-96ea-4807-aec1-3b3b559419b6
2022-09-22T02:59:13.037Z|200960|ovn_dbctl|INFO|Running command run -- set Load_Balancer 8ba7097d-fc98-4181-85a2-65168593b089 "vips:\"155.160.0.1:80\"=\"16.231.0.124:8080\""
2022-09-22T02:59:13.072Z|200961|ovn_dbctl|INFO|Running command run -- set Load_Balancer 37ddb7e1-60da-4b74-a501-429e299f10c9 "vips:\"155.160.0.1:80\"=\"16.231.0.124:8080\""
2022-09-22T02:59:13.078Z|200962|ovn_dbctl|INFO|Running command run -- set Load_Balancer 3cc166df-96ea-4807-aec1-3b3b559419b6 "vips:\"155.160.0.1:80\"=\"16.231.0.124:8080\""
```
So, I'm not sure if the change will actually help.

**Comment by dceara** [comment]
Oh, you're right.  We're incrementing the subnet instead of picking an IP from it.  That's wrong.  I'll reopen the issue.
